### ISSUE TITLE
Social Media Buttons

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#10]
1. Replace Github buttons with (clickable) icon to reduce space.
2. Move icons to top navigation menu bar, if possible (how they are displayed at scilifelab.se)
2. Maybe place button/icon for SciLifeLab's Github on 'Open Source' page.

**Comment by ewels** [comment]
1. Yup, good idea 👍 
2. Not keen on this sorry, not sure that we put enough effort in to these channels to make them such a high priority
3. Sure 👍 

For reference, this content is a _widget_ in the footer:
![image](https://user-images.githubusercontent.com/465550/73860492-ecb86800-483b-11ea-99b2-7a867b6c13a6.png)

In this case it's a custom widget provided in the theme. The code is here:
https://github.com/NationalGenomicsInfrastructure/ngisweden.se/blob/54aa1990ab95772467969a4eacd264d7dba91531/wp-content/themes/ngisweden/functions/widgets.php#L105-L148

**Comment by ewels** [comment]
Ok, I just used a free plugin instead of changing any code: https://wordpress.org/plugins/social-icons-widget-by-wpzoom/

![image](https://user-images.githubusercontent.com/465550/73861137-e5458e80-483c-11ea-95c6-f1550bd2e4d8.png)

It's now a lot easier to customise through the admin web back end too: 
![image](https://user-images.githubusercontent.com/465550/73861195-f4c4d780-483c-11ea-864d-d2a90dede31c.png)

https://ngisweden-dev.scilifelab.se/wp-admin/widgets.php

**Comment by Nazeeefa** [comment]
Cheers Phil! I am trying to figure out how to add Github icon (maybe as image?) next to links on Open Source page. I appreciate your help. Thanks.

**Comment by ewels** [comment]
Easiest is probably just to insert an image, yes.

If you're feeling fancy then you can edit it as a HTML block and use a font-awesome icon (the website uses these elsewhere I think, so should be available).

https://fontawesome.com/icons/github?style=brands

```html
<i class="fab fa-github"></i> <a href="https://github.com/whatever" target="_blank">link text</a>
```

**Comment by Nazeeefa** [comment]
Just making a note of what's been done:

Ideally, it would be good to have nested HTML block in grid with space and structure preserved for all elements in group/container - basically a custom grid. For now, the best solution is replacing a grid with simple columns and adding HTML block in each to display icons.

Example code: `<p style="text-align: center;"><span style="text-align: center; display: inline-block;" class="fas fa-icon fa-size" aria-hidden="true"></span></p>`
