### ISSUE TITLE
Publications: check for duplicate DOIs

### ISSUE THREAD

**Issue by ewels** [NationalGenomicsInfrastructure/ngisweden.se#11]
@nazeefa spotted two duplicate papers in a single list of publications. This isn’t the website’s fault, they were duplicate entries in the upstream database. Hopefully this will be fixed in the long run, but we could also check for duplicate DOIs when we make the list for the front end. Simple and shouldn’t hurt.

**Comment by Nazeeefa** [comment]
Just a tiny note; you tagged my old account in comment above :) no wonder I missed this haha

**Comment by ewels** [comment]
Ah oops, sorry!
