### ISSUE TITLE
Accordion block

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#12]
The purpose is to make content collapsible for, for example, following pages:

- New to NGI
- Frequently Asked Questions

Plugin https://gutenberghub.com/blocks/accordion-block-2/ unless it is already installed.

This will help avoid making page content appear lengthy and burdening user/reader with all content.

**Comment by ewels** [comment]
Gutenberg Hub? Awesome!

**Comment by ewels** [comment]
Ok, the plugin you found looks _amazing_... https://wpstackable.com/

Installing now to enable collapsible dropdowns, plus a tonne of other content blocks 👍

**Comment by ewels** [comment]
![image](https://user-images.githubusercontent.com/465550/74032058-5c049800-49b3-11ea-90e2-d2c6c1afe68d.png)


Done ✅

**Comment by Nazeeefa** [comment]
Great! Thank you. I think it would be very useful to have this for 'Deliveries' pages too.

**Comment by Nazeeefa** [comment]
Deliveries section sorted.
