### ISSUE TITLE
FAQs Section

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#13]
**Layout Ideas**
Suggestion: https://www.skinnydiplondon.com/pages/faq with preference (in terms of using relevant icons for each page/section): https://shwoodshop.com/pages/help#shipping-faq

**Comment by ewels** [comment]
I'd prefer not to have a single FAQ page if possible. Instead, we could just have multiple pages, one for each category? Using the links above as an example, a page for _Payments_, a page for _Delivery_ and so on..

Depends a little on what content we intend to have here I guess.

**Comment by Nazeeefa** [comment]
Would having multiple pages require less clicking? or do you mean multiple pages similar to shown in first link? I would prefer latter so user doesn't have to go back and forth to access different pages.

**Comment by ewels** [comment]
Multiple pages would be the same number of clicks. Just keeps the content more separate than having everything on one page so easier to maintain.

This comes back to me disliking pages called FAQ or miscellaneous etc. If users have a specific thing that they're looking for then they usually end up there as a last resort and end up having to read everything to find the one detail. I think it's better to keep pages as specific as possible for easier navigation. This is also better for ease of content maintenance.

**Comment by Nazeeefa** [comment]
I understand. One question, are we keeping FAQs (and some other _Order Portal_ related stuff) [here](https://ngisweden.scilifelab.se/) or planning to transfer content to integrate order portal?

One idea could be to spread FAQs to relevant pages (is that what you also had in mind when you mentioned multiple pages)? :) for example, questions in _submitting samples_ can be moved to _sample deliveries_ section (sub-section of _Deliveries_).

**Comment by ewels** [comment]
We are planning to remove all of the content - FAQs etc from the order portal and move that to the new website, yes. Then the order portal can be just for making orders and nothing else.

And yes - FAQs on relevant pages is exactly what I would like 😀

**Comment by Nazeeefa** [comment]
I'll take care of what I can :)

**Comment by Nazeeefa** [comment]
I have checked and placed FAQ content (excluding https://ngisweden.scilifelab.se/info/faq#what-does-the-order-status-preparation-submitted-etc-mean) to relevant pages/sections.
