### ISSUE TITLE
Navigation dropdowns on hover instead of click

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#14]
1. We need to make it responsive (in addition to multi-level drop-down menu) i.e. it toggles on mouseover.

**Comment by Nazeeefa** [comment]
2. We need to rearrange the sections as following (preliminary idea):
```
├── About us
|          ├── News & Events
|          └── Careers
├── Services
│         ├── Applications
│         │   ├── Epigenetics
│         │   └── Single-Cell
│         └── Technologies
│               ├── Illumina
│               └── PacBio
└── Resources
         ├── Bioinformatics
         │        └── Tech Notes or Open Source code
         └── Scientific Highlights
```

**Comment by ewels** [comment]
> We need to make it responsive (in addition to multi-level drop-down menu) i.e. it toggles on mouseover.

I don't understand what you mean here. It should be responsive on mobile / small screens - you'll get a menu icon that triggers the nav to show when tapped.

**Comment by ewels** [comment]
I still dislike multi-level navigations as a principle. Can we not just have top-level items for _Applications_ and _Technologies_?

**Comment by Nazeeefa** [comment]
> > We need to make it responsive (in addition to multi-level drop-down menu) i.e. it toggles on mouseover.
> 
> I don't understand what you mean here. It should be responsive on mobile / small screens - you'll get a menu icon that triggers the nav to show when tapped.

That's fine. I meant for desktop and by responsive I meant as in it doesn't require clicking on (e.g. _Application_) item to be able to open the drop-down. (See this page for example http://genomics.ed.ac.uk/)

**Comment by Nazeeefa** [comment]
> I still dislike multi-level navigations as a principle. Can we not just have top-level items for _Applications_ and _Technologies_?

Based on feedback, it's better if top-level item is "Services" that works as drop-down and gives two options i.e. Applications and Technologies (as shown in point 2).

Personally, having a look at nav meu bar again, I think multi-level navigation may not be necessary.

**Comment by ewels** [comment]
> by responsive I meant as in it doesn't require clicking on (e.g. Application) item to be able to open the drop-down.

Ok, so it unfurls on mouse hover you mean. Yeah I can look in to this. Navigation bars were typically made this way in the past, but in recent years it's been popular to require a click to unfurl. There is some kind of accessibility / user intent argument about this, but I don't really care too much.

**Comment by Nazeeefa** [comment]
> > by responsive I meant as in it doesn't require clicking on (e.g. Application) item to be able to open the drop-down.
> 
> Ok, so it unfurls on mouse hover you mean. Yeah I can look in to this. Navigation bars were typically made this way in the past, but in recent years it's been popular to require a click to unfurl. There is some kind of accessibility / user intent argument about this, but I don't really care too much.

Ok, I read few articles to understand better the pros and cons of hover vs click-on menus & the accessibility argument for not using hover makes sense. So, I leave this as suggestion i.e. let's implement it if possible (since I received a feedback that website navigation already requires a lot of clicking lol) otherwise let's stick to click-on menu 😊
