### ISSUE TITLE
Trashed pages show up on the site map

### ISSUE THREAD

**Issue by taborsak** [NationalGenomicsInfrastructure/ngisweden.se#16]

**Comment by Nazeeefa** [comment]
Aren't they supposed to be removed automatically after 30 days?

**Comment by ewels** [comment]
> Aren't they supposed to be removed automatically after 30 days?

Are they? I'm not sure if we want that..?

This was more that I had updated the site to show drafts on the front-end of the site. But I went a bit far with it and it also shows trashed pages as well.

Just needs nudging back to hide trashed posts on the front end. Again this will go away when the site goes live and I remove this behaviour.

**Comment by Nazeeefa** [comment]
Yeah it's a bit confusing when these pages appear on front-end, for example https://ngisweden-dev.scilifelab.se/methods/epic-methylation-array__trashed/ and even the section (box) for it appears here https://ngisweden-dev.scilifelab.se/applications/genotyping/ despite being put in the bin
