### ISSUE TITLE
Mail from webserver not working?

### ISSUE THREAD

**Issue by ewels** [NationalGenomicsInfrastructure/ngisweden.se#2]
@alneberg tried to reset his password and got the following error:

> The email could not be sent. Possible reason: your host may have disabled the `mail()` function.

**Comment by pekrau** [comment]
This is not the OrderPortal, is it?

**Comment by ewels** [comment]
Nope, this is https://ngisweden-dev.scilifelab.se/ - it will hopefully be a new website that is complementary to the OrderPortal.

**Comment by pekrau** [comment]
OK, phew...

**Comment by ewels** [comment]
This is now resolved.
