### ISSUE TITLE
Combine News and Events Page

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#20]
We can transfer content/design from Events page to News page, and rename the page (News & Events).

In addition, most of our events particularly collaborative ones get listed on SciLifeLab's website any way so that's another source to find our events.

**Comment by ewels** [comment]
This is impossible, as the Events page uses a separate plugin to handle maps, locations, user signup and so on.

We can remove this if we want, but that's a separate discussion. I mostly added it because I thought having user registration for events could be useful.

**Comment by Nazeeefa** [comment]
Okej, so it's not possible to integrate plugin on same page? hmm, events page with all details (except link and brief info) may not be necessary though - given that, as far as I know, majority of our events have/get details (registration, directions, date/time) listed on SciLifeLab's website. Unless, we want to keep traffic in our direction 😁

**Comment by ewels** [comment]
I don't see why we can't have event details on both websites.. It might make life a bit easier to have the scilifelab webpage listing fairly light, pointing to the ngi website event page. That way we can update the webpage as much as we like without relying on anyone else.
