### ISSUE TITLE
Suggestion: Anchor Links with Smooth Scrolling

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#23]
For pages that contain lengthy information e.g:

- Sample Submission / Data Delivery
- Bioinformatics Support (if/when this information https://ngisweden.scilifelab.se/info/bioinformatics is transferred to new webpage)

Relevant plugin: https://wordpress.org/plugins/page-scroll-to-id/

**Comment by silverslott** [comment]
Has been fixed now, with the accordions.
