### ISSUE TITLE
Test: Events Page & Plugin

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#24]
Current Plugin: [Events Manager](https://wp-events-plugin.com/) - apparently, it's [incompatible with Gutenberg](https://wp-events-plugin.com/blog/2018/12/06/wordpress-5-0-and-gutenberg-compatibility/).

Alternatives (if required):
- [The Events Calendar](https://wordpress.org/plugins/the-events-calendar/) (Github: https://github.com/moderntribe/events-gutenberg)
- [Munich (Event) block](https://wordpress.org/plugins/wp-munich-blocks/)

**Comment by ewels** [comment]
Are you sure it's incompatible? They say that they are using the classic editor for now and that they have started rewriting to use Gutenberg. The plugin seems to work fine as it is with the classic editor...

**Comment by Nazeeefa** [comment]
That's the impression I got even though it says:

> ...Events Manager is not compatible with the Gutenberg editor for now, but you can still manage your events the same way as before whilst still using Gutenberg on your posts, pages etc.

Let's try out this then :)

> We have been following the project for about a year now, and implemented optional support for Gutenberg in Events Manager 5.9.5

I understand however perhaps it's better to use something that requires less/no maintenance? You probably know better. Sorry, I do not know. Cheers!

**Comment by ewels** [comment]
Sorry, I was misreading a bit. You're right - incompatible with Gutenberg, but not incompatible with WordPress. As long as it's still compatible with our version of WordPress I don't think I mind too much..

**Comment by Nazeeefa** [comment]
No worries. Let's test with lrua2020.se? 😸

I have noticed a few things for now:

1) was unable to view featured image when I view the page.
2) For location i.e. when you click on e.g. SciLifeLab Uppsala, it doesn't have to have a new link/page showing (SciLifeLab node) address as event venue can be different (e.g. hotel or university main building, etc).

**Comment by ewels** [comment]
1. Yes, I guess I need to write some theme template pages for events so that the output is formatted nicely.
2. I don't totally understand the question, but you can add new locations to the dropdown [here](https://ngisweden-dev.scilifelab.se/wp-admin/edit.php?post_type=location).

**Comment by ewels** [comment]
Ok I just put a quick theme template together for events - testing locally it looked like this:

![image](https://user-images.githubusercontent.com/465550/79041843-4437d300-7bf3-11ea-8367-4f95c58a2d41.png)

Please have a play and let me know if you find any bugs, or content you add doesn't show up (I've manually added fields so may have missed some).

Phil

**Comment by Nazeeefa** [comment]
Thanks! About second point, it was a comment 😄When you click on location name (right sidebar) it takes you to [this page](https://ngisweden-dev.scilifelab.se/locations/scilifelab-uppsala/) that also mentions address. So I was wondering, either we 1) get rid of creating-new-page-for-location feature, 2) convert location category to host/organiser? that displays only name (and not address), or 3) keep location but make compulsory fields optional.

<img width="885" alt="Events_Locations_ngi" src="https://user-images.githubusercontent.com/6730853/79206647-ef3ccc80-7e3f-11ea-94fe-129ff777e606.png">

**Comment by ewels** [comment]
So options 1-3 are not going to happen as they would require heavy modification to the plugin 😓 But I could just remove the link to the location page?

**Comment by ewels** [comment]
Ok, I removed the link and I think it looks better 👍 

Note that I don't think the Categories should have stuff like _NGI Uppsala_, as that's a location really. Could be good to make events like _Meetings_, _Seminars_, _Conferences_, _Webinars_ etc..
