### ISSUE TITLE
Suggestion: Add a Scroll-to-Top Button

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#27]
For pages e.g:
- Contact Us Page
- Sample Submission
- Data Delivery
- News, once more posts are added
- bioinformatics (analysis) pages for applications

**Comment by ewels** [comment]
Good idea 👍 

What do you think about adding this to the general template footer for all pages? Maybe just above the footer on the right hand side (above the SciLifeLab logo).

**Comment by Nazeeefa** [comment]
So, I have been reading about this; adding this for all pages is (not necessary but also) not a bad idea as long as the button is not always visible/interactive, and remains in that state until the user needs it. However, it is particularly useful for pages with lengthy information. [Basecamp](https://m.signalvnoise.com/how-to-back-to-top-button-without-scroll-events/) has implemented this using [intersection observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API).

**Comment by silverslott** [comment]
I added it, what do you think? :-)

**Comment by ewels** [comment]
Awesome! 🎉 👏🏻 

Only problem is that it doesn't seem to work on mobile for me, which was kind of the whole point 😅

**Comment by silverslott** [comment]
Oh, I disabled it for small devices! I can enable it! 👍

**Comment by silverslott** [comment]
Should work now!

**Comment by ewels** [comment]
![fast](https://c.tenor.com/MmqLTk0Wk-EAAAAC/twas-so-fast-so-fast.gif)

**Comment by ewels** [comment]
Awesome 💥
