### ISSUE TITLE
Create multilevel menus

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#3]
Enhancement to navigation bar for easy to access. For example:

Applications > Bioinformatics > 
* Bioinformatics Support by NGI Stockholm
* Bioinformatics Support by NGI Uppsala

**Comment by ewels** [comment]
Main nav is currently limited to depth 2 [here](https://github.com/NationalGenomicsInfrastructure/ngisweden.se/blob/439c725ebfd7617adbd32f5a33e2d454d017d1ad/wp-content/themes/ngisweden/header.php#L33). Easy to update, but need to check that the [bs4navwalker](https://github.com/NationalGenomicsInfrastructure/ngisweden.se/blob/master/wp-content/themes/ngisweden/includes/bs4navwalker.php) can handle menus with depth > 2...

**Comment by ewels** [comment]
Closing this issue for now, as I deleted the two Stockholm / Uppsala specific pages mentioned above (sorry 🙄 - still saved in the bin for now if you need any content back). I think that the content that they described is better placed in specific bioinformatics pages associated with different methods.

If I'm honest, I prefer to avoid multi-level navigations where I can, instead simplifying content and number of pages. But we can come back and reopen this issue at a later date if we feel that we really need them.

**Comment by Nazeeefa** [comment]
No worries. However, multi-level drop-down menu would be useful for, for example, _**Applications**_ section. I had a look at the section with one of my colleagues and we feel that it gets confusing which sub-section belongs where. So, it would be helpful to make use of multi-level navigation once all sections are finalized. This will help to avoid lots of clicking for going back and forth.

![ngiSE_applications](https://user-images.githubusercontent.com/6730853/73743786-a7b70780-474f-11ea-9eb3-87c49464fa55.png)
