### ISSUE TITLE
Suggestion: Multi-column dropdown

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#30]
I understand I said it looks great 😄and it does! However, we can improve it; the drop-down for **_Services_** appear lengthy and space-consuming - my suggestion is to convert it to multi-column dropdown.

**Comment by silverslott** [comment]
Suggestion:

![Skärmavbild 2023-04-05 kl  14 19 29](https://user-images.githubusercontent.com/37932118/230078474-3e27ee2b-bc30-4900-863f-00885c1ec7dd.png)

**Comment by silverslott** [comment]
Implemented in https://github.com/NationalGenomicsInfrastructure/ngisweden.se/pull/43
