### ISSUE TITLE
URL is https://ngisweden.scilifelab.se/ instead of https://ngisweden.se/ ?

### ISSUE THREAD

**Issue by richelbilderbeek** [NationalGenomicsInfrastructure/ngisweden.se#40]
Dear maintainers,

At the main NGI GitHub organistion page at https://github.com/NationalGenomicsInfrastructure the URL used is https://ngisweden.se/ . It is too bad, that one does not work. However, https://ngisweden.scilifelab.se/ works great. 

Maybe the short URL will be the one used in the future, in which case this Issue will be obsolete. If, however, it is simply not yet updated to use https://ngisweden.scilifelab.se/ , I hope this Issue is appreciated :-)

Cheers, Richel Bilderbeek

**Comment by silverslott** [comment]
Thank you so much for letting us know! We are currently looking into this.

**Comment by silverslott** [comment]
OK, so the redirection of _https://ngisweden.se_ does not work, but _http://ngisweden.se_ does work. 

We simply changed the url in the readme 🤷🏻‍♀️
