### ISSUE TITLE
Science Highlights

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#9]
Remove repeated entries.

**How it works:** "The list always contains some papers that we have collaborated on
otherwise these would generally be drowned out and not show up very often. So, the list on the left has been specified to give only collaboration papers `(num=10 collabs=10)` and the one on the right has the default number of _collabs_

**Problem**: "Because both lists have `randomise=0` set, they will be printed in age order, so that means that there is guaranteed to be one collaborative paper duplicated in the lists"

**Solution**: Add a new argument `max_collabs`

Thanks, @ewels!

**Comment by Nazeeefa** [comment]
Replace 'Science' with 'Scientific'.

**Comment by ewels** [comment]
Hi @Nazeeefa,

Are you planning to make these changes yourself and just noting them here for reference, or are you requesting someone else makes the change? If in doubt, feel free to just change this 😊 

Phil

**Comment by Nazeeefa** [comment]
Hi Phil, just noting them here (as issues) to keep a track of what we can fix and improve. Hope that's fine :) & Thank you. Cheers!

**Comment by ewels** [comment]
Absolutely!
